import { getRecentElementsFromArray } from './data-helpers.js';

// tests initially generated by Claude LLM - reviewed by a human :)
describe('getRecentElementsFromArray', () => {
  it('should return empty array when given an empty array', () => {
    const result = getRecentElementsFromArray([], 'timestamp', 5);
    expect(result).toEqual([]);
  });

  it('should return ordered elements when array size is less than count', () => {
    const array = [
      { id: 1, hiddenAtTs: 100 },
      { id: 2, hiddenAtTs: 200 },
      { id: 3, hiddenAtTs: 150 },
    ];
    const result = getRecentElementsFromArray(array, 'hiddenAtTs', 5);
    expect(result.map((el) => el.id)).toEqual([2, 3, 1]);
  });

  it('should return only the most recent elements, in order, up to count', () => {
    const array = [
      { id: 1, hiddenAtTs: 100 },
      { id: 2, hiddenAtTs: 500 },
      { id: 3, hiddenAtTs: 300 },
      { id: 4, hiddenAtTs: 400 },
      { id: 5, hiddenAtTs: 200 },
    ];
    const result = getRecentElementsFromArray(array, 'hiddenAtTs', 3);
    expect(result).toHaveLength(3);
    // Should contain the 3 most recent timestamps: 500, 400, 300
    expect(result.map((el) => el.hiddenAtTs)).toEqual([500, 400, 300]);
  });

  it('should skip elements with missing or falsy timestamp', () => {
    const array = [
      { id: 1, hiddenAtTs: 100 },
      { id: 2, hiddenAtTs: null },
      { id: 3, hiddenAtTs: 300 },
      { id: 4 }, // missing hiddenAtTs
      { id: 5, hiddenAtTs: 200 },
    ];
    const result = getRecentElementsFromArray(array, 'hiddenAtTs', 5);
    expect(result).toHaveLength(3);
    expect(result.map((el) => el.id)).toEqual([3, 5, 1]);
  });

  it('should handle count of 1', () => {
    const array = [
      { id: 1, hiddenAtTs: 100 },
      { id: 2, hiddenAtTs: 500 },
      { id: 3, hiddenAtTs: 300 },
    ];
    const result = getRecentElementsFromArray(array, 'hiddenAtTs', 1);
    expect(result).toHaveLength(1);
    expect(result[0].hiddenAtTs).toBe(500);
  });

  it('should handle duplicate timestamps', () => {
    const array = [
      { id: 1, hiddenAtTs: 100 },
      { id: 2, hiddenAtTs: 300 },
      { id: 3, hiddenAtTs: 300 },
      { id: 4, hiddenAtTs: 200 },
    ];
    const result = getRecentElementsFromArray(array, 'hiddenAtTs', 3);
    expect(result).toHaveLength(3);
    expect(result.map((el) => el.id)).toEqual([2, 3, 4]);
  });

  it('should handle zero count', () => {
    const array = [
      { id: 1, hiddenAtTs: 100 },
      { id: 2, hiddenAtTs: 200 },
    ];
    const result = getRecentElementsFromArray(array, 'hiddenAtTs', 0);
    expect(result).toEqual([]);
  });

  it('should preserve all object properties', () => {
    const array = [
      { id: 1, hiddenAtTs: 100, name: 'first', extra: 'data1' },
      { id: 2, hiddenAtTs: 200, name: 'second', extra: 'data2' },
    ];
    const result = getRecentElementsFromArray(array, 'hiddenAtTs', 2);
    expect(result[0]).toEqual({
      id: 2,
      hiddenAtTs: 200,
      name: 'second',
      extra: 'data2',
    });
    expect(result[1]).toEqual({
      id: 1,
      hiddenAtTs: 100,
      name: 'first',
      extra: 'data1',
    });
  });
});
