// Example API calls and responses.

// https://api-v2.soundcloud.com/me?client_id=[CLIENT_ID]&oauth_token=[OAUTH_TOKEN]

const me_response_json = {
  avatar_url: 'https://i1.sndcdn.com/avatars-qV4K8CgQeXU1XzBG-zXIA9g-large.jpg',
  blocked_tracks_count: 0,
  city: 'San Francisco',
  comments_count: 0,
  consumer_subscriptions: null,
  consumer_subscription: {
    product: {
      id: 'consumer-high-tier',
    },
  },
  country_code: 'US',
  cpp: null,
  created_at: '2012-09-18T20:43:11Z',
  creator_subscriptions: [
    {
      product: {
        id: 'creator-pro-unlimited',
      },
    },
  ],
  creator_subscription: {
    product: {
      id: 'creator-pro-unlimited',
    },
  },
  date_of_birth: {
    month: 0,
    year: 0,
  },
  default_license: 'all-rights-reserved',
  default_tracks_feedable: false,
  description:
    'CushionCut = Breakbeats & Contemporary Bass\nMoonwoofer = Late night bass / halftime / 2step / wave / etc\n\nBurningman Camps: Shackleton, Secret Location\nParties: Something Else, Tupper, Superhaus NYE, FnF\n\nOwner @ Moonwoofer sound system.',
  downloads_disabled: false,
  downloads_disabled_reason: '',
  first_name: 'Mark',
  followers_count: 79,
  followings_count: 289,
  full_name: 'Mark W',
  gender: 'male',
  groups_count: 0,
  hidden_tracks_count: 0,
  id: 24419296,
  kind: 'user',
  last_modified: '2024-06-24T06:52:41Z',
  last_name: 'W',
  likes_count: 814,
  playlist_likes_count: 16,
  locale: 'en',
  permalink: 'cushioncut',
  permalink_url: 'https://soundcloud.com/cushioncut',
  playlist_count: 8,
  primary_email: 'x',
  primary_email_confirmed: true,
  primary_email_sha256: 'X',
  private_playlists_count: 37,
  private_tracks_count: 0,
  quota: {
    unlimited_upload_quota: true,
    upload_seconds_used: 18501,
    upload_tracks_used: 4,
    unlimited_upload_duration_quota: true,
    unlimited_upload_track_quota: true,
  },
  reposts_count: 1,
  track_count: 4,
  urn: 'soundcloud:users:24419296',
  uri: 'https://api.soundcloud.com/users/24419296',
  username: 'CushionCut | Moonwoofer',
  verified: false,
  visuals: {
    urn: 'soundcloud:users:24419296',
    enabled: true,
    visuals: [
      {
        urn: 'soundcloud:visuals:50527924',
        entry_time: 0,
        visual_url:
          'https://i1.sndcdn.com/visuals-000024419296-dAY9K8-original.jpg',
      },
    ],
    tracking: null,
  },
  confirmed: true,
  badges: {
    pro: false,
    creator_mid_tier: false,
    pro_unlimited: true,
    verified: false,
  },
  analytics_id: null,
  consent_management_jwt: {
    userId: 'X',
    jwt: 'X',
  },
  station_urn: 'soundcloud:system-playlists:artist-stations:24419296',
  station_permalink: 'artist-stations:24419296',
  marketing_ids: {
    gtm: 'X',
  },
  ppid: 'X',
  spotlight_limit: 5,
};

// https://api-v2.soundcloud.com/resolve?url=http://soundcloud.com/saturaterecords/subp-yao-rattle-9&client_id=[CLIENT_ID]&oauth_token=[OAUTH_TOKEN]

const resolve_response_json = {
  artwork_url:
    'https://i1.sndcdn.com/artworks-myHSoWuVxTwpITyN-YlcYuA-large.png',
  caption: null,
  commentable: true,
  comment_count: 1,
  created_at: '2025-05-19T20:10:59Z',
  description:
    '"Nothing unearths precious metals like an earthquake, after all, and the snares on ‘Rattle’ take on the frantic scribbling of a seismic tracker as the bass and sub bass grind and roll against each other." - Layla Marino\n\n🏆 CHECK OUT THE KMAG PREMIERE:\nhttps://kmag.co.uk/premiere-subp-yao-set-to-rattle-some-cages-with-new-experimental-bass-offering-soil-saturate/\n\nBuried in the dirt, the conscience has room to germinate. Continuing to take root in the underground, Subp Yao gets them hands engulfed in the mud. Finally harvesting fruit of labour planted beyond grassroots level, "Soil" demonstrates Subp Yao\'s cultivation of sound expanding further than the sands of time. \n\n"Soil" is deeply entrenched in the underground, rattling sub frequencies to disturb the streets. We\'re honoured to have SATURATE! submerged in the "Soil" for this release. \n\n🪨 Subp Yao \n\n🪨 sc: [ https://soundcloud.com/subpyao ] \n🪨 ig: [ https://www.instagram.com/subpyaooo/ ] \n\n🎨 art: Thomas Wahle\n\n🌍 SATURATE! 🌍\n\n🌍 discord: [  https://discord.gg/saturate ]\n🌍 patreon: [  https://patreon.com/SATURATE ]\n🌍 artist dev: [  https://feedback.aboveandbelow.co ]\n🌍 web: [ https://www.saturaterecords.com ]',
  downloadable: false,
  download_count: 0,
  duration: 169760,
  full_duration: 169744,
  embeddable_by: 'all',
  genre: 'Electronic',
  has_downloads_left: false,
  id: 2098681506,
  kind: 'track',
  label_name: 'SATURATE! ',
  last_modified: '2025-06-03T19:49:27Z',
  license: 'all-rights-reserved',
  likes_count: 53,
  permalink: 'subp-yao-rattle-9',
  permalink_url: 'https://soundcloud.com/saturaterecords/subp-yao-rattle-9',
  playback_count: 904,
  public: true,
  publisher_metadata: {
    id: 2098681506,
    urn: 'soundcloud:tracks:2098681506',
    artist: 'Subp Yao',
    album_title: 'Soil (STRTLP018)',
    contains_music: true,
    publisher: 'SATURATE!',
    isrc: 'QM8DG2545232',
    explicit: false,
    p_line: 'SATURATE! 2025',
    p_line_for_display: '℗ SATURATE! 2025',
    writer_composer: 'Gert-Jan van Stiphout',
    release_title: 'Rattle',
  },
  purchase_title: 'GET IT HERE',
  purchase_url: 'https://subpyao.bandcamp.com/album/soil-strtlp018',
  release_date: '2025-06-03T00:00:00Z',
  reposts_count: 2,
  secret_token: null,
  sharing: 'public',
  state: 'finished',
  streamable: true,
  tag_list:
    'halftime wonky beats hyphy underground "future beats" dubstep "bass hop" ukg 2step ukbass acid breaks "bass music"',
  title: 'Subp Yao - Rattle [KMAG Premiere]',
  uri: 'https://api.soundcloud.com/tracks/2098681506',
  urn: 'soundcloud:tracks:2098681506',
  user_id: 1455094,
  visuals: null,
  waveform_url: 'https://wave.sndcdn.com/TYz6euRXA98X_m.json',
  display_date: '2025-06-03T19:49:27Z',
  media: {
    transcodings: [
      {
        url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:2098681506/b83f8e7c-3310-4349-8ab1-77e7621ba10d/stream/hls',
        preset: 'aac_256k',
        duration: 169760,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/mp4; codecs="mp4a.40.2"',
        },
        quality: 'hq',
        is_legacy_transcoding: false,
      },
      {
        url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:2098681506/f5bb26ff-8a17-428b-9e4a-38c96e497889/stream/hls',
        preset: 'abr_hq',
        duration: 169760,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/mpegurl',
        },
        quality: 'hq',
        is_legacy_transcoding: false,
      },
      {
        url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:2098681506/2834c0af-622f-42c9-8f08-dd9ffd46e5ff/stream/hls',
        preset: 'aac_1_0',
        duration: 169736,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/mp4; codecs="mp4a.40.2"',
        },
        quality: 'hq',
        is_legacy_transcoding: true,
      },
      {
        url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:2098681506/2834c0af-622f-42c9-8f08-dd9ffd46e5ff/stream/progressive',
        preset: 'aac_1_0',
        duration: 169736,
        snipped: false,
        format: {
          protocol: 'progressive',
          mime_type: 'audio/mp4; codecs="mp4a.40.2"',
        },
        quality: 'hq',
        is_legacy_transcoding: true,
      },
      {
        url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:2098681506/2ab10740-f32c-4578-a06e-3d05121fb495/stream/hls',
        preset: 'aac_160k',
        duration: 169760,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/mp4; codecs="mp4a.40.2"',
        },
        quality: 'sq',
        is_legacy_transcoding: false,
      },
      {
        url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:2098681506/487ba21a-8588-4b35-9251-e26578a7f27c/stream/hls',
        preset: 'abr_sq',
        duration: 169760,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/mpegurl',
        },
        quality: 'sq',
        is_legacy_transcoding: false,
      },
      {
        url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:2098681506/b707c5c7-cdda-44d6-97fa-f19502f51b05/stream/hls',
        preset: 'mp3_1_0',
        duration: 169744,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/mpeg',
        },
        quality: 'sq',
        is_legacy_transcoding: true,
      },
      {
        url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:2098681506/b707c5c7-cdda-44d6-97fa-f19502f51b05/stream/progressive',
        preset: 'mp3_1_0',
        duration: 169744,
        snipped: false,
        format: {
          protocol: 'progressive',
          mime_type: 'audio/mpeg',
        },
        quality: 'sq',
        is_legacy_transcoding: true,
      },
      {
        url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:2098681506/c0a9781f-d8db-49aa-b1b8-5efe289d8b6e/stream/hls',
        preset: 'opus_0_0',
        duration: 169721,
        snipped: false,
        format: {
          protocol: 'hls',
          mime_type: 'audio/ogg; codecs="opus"',
        },
        quality: 'sq',
        is_legacy_transcoding: true,
      },
    ],
  },
  station_urn: 'soundcloud:system-playlists:track-stations:2098681506',
  station_permalink: 'track-stations:2098681506',
  track_authorization: 'X',
  monetization_model: 'AD_SUPPORTED',
  policy: 'MONETIZE',
  user: {
    avatar_url:
      'https://i1.sndcdn.com/avatars-lmd5worH2ovAatFV-ji10zQ-large.jpg',
    city: '',
    comments_count: 0,
    country_code: null,
    created_at: '2010-08-05T11:07:34Z',
    creator_subscriptions: [
      {
        product: {
          id: 'creator-pro-unlimited',
        },
      },
    ],
    creator_subscription: {
      product: {
        id: 'creator-pro-unlimited',
      },
    },
    description:
      'SATURATE! is a digital and vinyl label for fresh music. Bringing you the heat since 2010.\n\nfollow our sister channel @soundmuseum',
    followers_count: 30840,
    followings_count: 943,
    first_name: '',
    full_name: '',
    groups_count: 0,
    id: 1455094,
    kind: 'user',
    last_modified: '2025-06-11T17:58:06Z',
    last_name: '',
    likes_count: 1886,
    playlist_likes_count: 243,
    permalink: 'saturaterecords',
    permalink_url: 'https://soundcloud.com/saturaterecords',
    playlist_count: 108,
    reposts_count: null,
    track_count: 632,
    uri: 'https://api.soundcloud.com/users/1455094',
    urn: 'soundcloud:users:1455094',
    username: 'SATURATE!',
    verified: true,
    visuals: {
      urn: 'soundcloud:users:1455094',
      enabled: true,
      visuals: [
        {
          urn: 'soundcloud:visuals:198648123',
          entry_time: 0,
          visual_url:
            'https://i1.sndcdn.com/visuals-000001455094-kK1Bgv-original.jpg',
        },
      ],
      tracking: null,
    },
    badges: {
      pro: false,
      creator_mid_tier: false,
      pro_unlimited: true,
      verified: true,
    },
    station_urn: 'soundcloud:system-playlists:artist-stations:1455094',
    station_permalink: 'artist-stations:1455094',
  },
};

// playlists
// https://api-v2.soundcloud.com/playlists/2036367822?client_id=[CLIENT_ID]&oauth_token=[OAUTH_TOKEN]

const playlist_response_json = {
  artwork_url: null,
  created_at: '2025-06-13T06:17:27Z',
  description: '',
  duration: 286093,
  embeddable_by: 'all',
  genre: '',
  id: 2036367822,
  kind: 'playlist',
  label_name: '',
  last_modified: '2025-06-23T20:41:00Z',
  license: 'all-rights-reserved',
  likes_count: 0,
  managed_by_feeds: false,
  permalink: 'dig-2025h2',
  permalink_url: 'https://soundcloud.com/cushioncut/sets/dig-2025h2/[SECRET]',
  public: false,
  purchase_title: null,
  purchase_url: null,
  release_date: null,
  reposts_count: 0,
  secret_token: '[SECRET]',
  sharing: 'private',
  tag_list: '',
  title: 'Dig 2025H2',
  uri: 'https://api.soundcloud.com/playlists/2036367822?secret_token=[SECRET]',
  user_id: 24419296,
  set_type: '',
  is_album: false,
  published_at: '2025-06-13T06:17:27Z',
  display_date: '2025-06-13T06:17:27Z',
  user: {
    avatar_url:
      'https://i1.sndcdn.com/avatars-qV4K8CgQeXU1XzBG-zXIA9g-large.jpg',
    first_name: 'Mark',
    followers_count: 79,
    full_name: 'Mark W',
    id: 24419296,
    kind: 'user',
    last_modified: '2024-06-24T06:52:41Z',
    last_name: 'W',
    permalink: 'cushioncut',
    permalink_url: 'https://soundcloud.com/cushioncut',
    uri: 'https://api.soundcloud.com/users/24419296',
    urn: 'soundcloud:users:24419296',
    username: 'CushionCut | Moonwoofer',
    verified: false,
    city: 'San Francisco',
    country_code: 'US',
    badges: {
      pro: false,
      creator_mid_tier: false,
      pro_unlimited: true,
      verified: false,
    },
    station_urn: 'soundcloud:system-playlists:artist-stations:24419296',
    station_permalink: 'artist-stations:24419296',
  },
  tracks: [
    {
      artwork_url:
        'https://i1.sndcdn.com/artworks-YNztEqdMtdv1JIDj-Vbo1Sw-large.jpg',
      caption: null,
      commentable: true,
      comment_count: 669,
      created_at: '2024-11-20T01:52:21Z',
      description: '',
      downloadable: false,
      download_count: 0,
      duration: 121431,
      full_duration: 121417,
      embeddable_by: 'all',
      genre: 'Trap',
      has_downloads_left: false,
      id: 1962407595,
      kind: 'track',
      label_name: '',
      last_modified: '2024-11-21T23:04:01Z',
      license: 'all-rights-reserved',
      likes_count: 1813,
      permalink: 'doechii-nissan-altima-merricat',
      permalink_url:
        'https://soundcloud.com/merricatblack/doechii-nissan-altima-merricat',
      playback_count: 22854,
      public: true,
      publisher_metadata: {
        id: 1962407595,
        urn: 'soundcloud:tracks:1962407595',
        artist: 'Merricat Black',
        explicit: false,
      },
      purchase_title: 'Free Download',
      purchase_url:
        'https://hypeddit.com/merricatblack/doechiinissanaltimamerricatblackflip',
      release_date: '2024-11-16T00:00:00Z',
      reposts_count: 627,
      secret_token: null,
      sharing: 'public',
      state: 'finished',
      streamable: true,
      tag_list: 'doechii "nissan altima" "merricat black"',
      title: 'Doechii - NISSAN ALTIMA (Merricat Black Flip)',
      uri: 'https://api.soundcloud.com/tracks/1962407595',
      urn: 'soundcloud:tracks:1962407595',
      user_id: 149548949,
      visuals: null,
      waveform_url: 'https://wave.sndcdn.com/ohW7yJevOW4i_m.json',
      display_date: '2024-11-21T23:04:01Z',
      media: {
        transcodings: [
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1962407595/f958081b-af72-4d5e-ba81-17b239e31e7e/stream/hls',
            preset: 'aac_256k',
            duration: 121431,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mp4; codecs="mp4a.40.2"',
            },
            quality: 'hq',
            is_legacy_transcoding: false,
          },
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1962407595/48688923-b943-4b58-aa78-413bcf4df2f2/stream/hls',
            preset: 'abr_hq',
            duration: 121431,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpegurl',
            },
            quality: 'hq',
            is_legacy_transcoding: false,
          },
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1962407595/852f3bd8-e2ba-4323-af60-9f523ac820fa/stream/hls',
            preset: 'aac_1_0',
            duration: 121406,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mp4; codecs="mp4a.40.2"',
            },
            quality: 'hq',
            is_legacy_transcoding: true,
          },
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1962407595/852f3bd8-e2ba-4323-af60-9f523ac820fa/stream/progressive',
            preset: 'aac_1_0',
            duration: 121406,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mp4; codecs="mp4a.40.2"',
            },
            quality: 'hq',
            is_legacy_transcoding: true,
          },
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1962407595/3cde81f4-14e4-4d59-be5c-0fa99347b319/stream/hls',
            preset: 'aac_160k',
            duration: 121431,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mp4; codecs="mp4a.40.2"',
            },
            quality: 'sq',
            is_legacy_transcoding: false,
          },
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1962407595/6c30e6e3-c47e-4c10-aefa-2afd0d9bfacc/stream/hls',
            preset: 'abr_sq',
            duration: 121431,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpegurl',
            },
            quality: 'sq',
            is_legacy_transcoding: false,
          },
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1962407595/acef90b1-55b2-4319-9709-3d0d09a36e37/stream/hls',
            preset: 'mp3_1_0',
            duration: 121417,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
            is_legacy_transcoding: true,
          },
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1962407595/acef90b1-55b2-4319-9709-3d0d09a36e37/stream/progressive',
            preset: 'mp3_1_0',
            duration: 121417,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
            is_legacy_transcoding: true,
          },
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1962407595/37ef1c09-0213-4007-adac-453f99b6c0c9/stream/hls',
            preset: 'opus_0_0',
            duration: 121391,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/ogg; codecs="opus"',
            },
            quality: 'sq',
            is_legacy_transcoding: true,
          },
        ],
      },
      station_urn: 'soundcloud:system-playlists:track-stations:1962407595',
      station_permalink: 'track-stations:1962407595',
      track_authorization:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJVUyIsInN1YiI6IjI0NDE5Mjk2IiwicmlkIjoiMjkwMDAwZjQtM2NiNi00ZmQ3LTkwMjUtNjAxZTc4YmE3MTFhIiwiaWF0IjoxNzUwODE5Njg2fQ.f-RzkBvjlaWWdqWMA_94_FaWiM92_9wnKz-LFJuwTXc',
      monetization_model: 'NOT_APPLICABLE',
      policy: 'ALLOW',
      user: {
        avatar_url:
          'https://i1.sndcdn.com/avatars-gsr1f2nQCVCDjCXt-9NUmvA-large.jpg',
        first_name: '?️  the man w/ eyes ?️',
        followers_count: 6736,
        full_name: '?️  the man w/ eyes ?️',
        id: 149548949,
        kind: 'user',
        last_modified: '2025-05-20T18:10:34Z',
        last_name: '',
        permalink: 'merricatblack',
        permalink_url: 'https://soundcloud.com/merricatblack',
        uri: 'https://api.soundcloud.com/users/149548949',
        urn: 'soundcloud:users:149548949',
        username: 'Merricat Black',
        verified: false,
        city: 'Portland, OR',
        country_code: null,
        badges: {
          pro: false,
          creator_mid_tier: false,
          pro_unlimited: true,
          verified: false,
        },
        station_urn: 'soundcloud:system-playlists:artist-stations:149548949',
        station_permalink: 'artist-stations:149548949',
      },
    },
    {
      artwork_url:
        'https://i1.sndcdn.com/artworks-IQ2PwhDSSIoV0zNj-vdkHxA-large.jpg',
      caption: null,
      commentable: true,
      comment_count: 71,
      created_at: '2023-05-20T10:15:37Z',
      description:
        'do i look lonely?\n‎ \n[REDACTED]\n‎ \nyou caused that.\n‎ \n\n[INTERLUDE]\n‎ \n\nOriginal Song: Willix - Dolorem\nhttps://soundcloud.com/willixbeats/dolorem\n‎ \n\n[SELF-DESTRUCTION]\n‎ \n\nspringtail. \n‎enjoy \u003C3',
      downloadable: false,
      download_count: 0,
      duration: 164664,
      full_duration: 164676,
      embeddable_by: 'all',
      genre: 'BREAKDOWN',
      has_downloads_left: false,
      id: 1518333106,
      kind: 'track',
      label_name: null,
      last_modified: '2025-05-27T13:22:52Z',
      license: 'all-rights-reserved',
      likes_count: 266,
      permalink: 'dolorem',
      permalink_url: 'https://soundcloud.com/rewqu/dolorem',
      playback_count: 9232,
      public: true,
      publisher_metadata: {
        id: 1518333106,
        urn: 'soundcloud:tracks:1518333106',
        contains_music: true,
        explicit: false,
        writer_composer: 'Muhammet Vance',
        release_title: 'dolorem',
      },
      purchase_title: 'SPOTIFY',
      purchase_url: 'https://open.spotify.com/artist/4FeqD3VKkTmXdHJmcpJPSx',
      release_date: '2023-05-20T00:00:00Z',
      reposts_count: 66,
      secret_token: null,
      sharing: 'public',
      state: 'finished',
      streamable: true,
      tag_list:
        'réwqu dolorem "NINE OF PARADISE" Willix dreamscape Ambient Audio "edit audio" edited reverb slowed "slowed and reverb" "slowed & reverb" "slowed down" "low pitch " extended perfection "extended to perfection" Sad tiktok "tiktok edit" dickcock trend "tiktok version" Wave Chill 2023',
      title: 'dolorem',
      uri: 'https://api.soundcloud.com/tracks/1518333106',
      urn: 'soundcloud:tracks:1518333106',
      user_id: 974750107,
      visuals: null,
      waveform_url: 'https://wave.sndcdn.com/m5GoiyKy9cFl_m.json',
      display_date: '2023-05-20T11:18:28Z',
      media: {
        transcodings: [
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1518333106/16f7d7d2-eedf-44fe-a562-b7c26eb2ae21/stream/hls',
            preset: 'aac_1_0',
            duration: 164664,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mp4; codecs="mp4a.40.2"',
            },
            quality: 'hq',
            is_legacy_transcoding: true,
          },
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1518333106/16f7d7d2-eedf-44fe-a562-b7c26eb2ae21/stream/progressive',
            preset: 'aac_1_0',
            duration: 164664,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mp4; codecs="mp4a.40.2"',
            },
            quality: 'hq',
            is_legacy_transcoding: true,
          },
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1518333106/dba4a907-5e13-459f-bb4c-4866dcffb59d/stream/hls',
            preset: 'mp3_1_0',
            duration: 164676,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
            is_legacy_transcoding: true,
          },
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1518333106/dba4a907-5e13-459f-bb4c-4866dcffb59d/stream/progressive',
            preset: 'mp3_1_0',
            duration: 164676,
            snipped: false,
            format: {
              protocol: 'progressive',
              mime_type: 'audio/mpeg',
            },
            quality: 'sq',
            is_legacy_transcoding: true,
          },
          {
            url: 'https://api-v2.soundcloud.com/media/soundcloud:tracks:1518333106/8b08a0a6-6f42-4561-9d54-a6a327ef4a48/stream/hls',
            preset: 'opus_0_0',
            duration: 164649,
            snipped: false,
            format: {
              protocol: 'hls',
              mime_type: 'audio/ogg; codecs="opus"',
            },
            quality: 'sq',
            is_legacy_transcoding: true,
          },
        ],
      },
      station_urn: 'soundcloud:system-playlists:track-stations:1518333106',
      station_permalink: 'track-stations:1518333106',
      track_authorization:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJnZW8iOiJVUyIsInN1YiI6IjI0NDE5Mjk2IiwicmlkIjoiYzQ4NDZlM2YtZWE4Ni00OGVhLWE2MGMtYmRkZWM3NDZhN2FjIiwiaWF0IjoxNzUwODE5Njg2fQ.aaEE4KaanHlkt4yvBPIhhfRYoLModPAwyFv_IlN-Ark',
      monetization_model: 'BLACKBOX',
      policy: 'MONETIZE',
      user: {
        avatar_url:
          'https://i1.sndcdn.com/avatars-CWVdbGaq2VGqALM2-Vmx3Jw-large.jpg',
        first_name: '',
        followers_count: 2201,
        full_name: '',
        id: 974750107,
        kind: 'user',
        last_modified: '2025-06-20T18:22:56Z',
        last_name: '',
        permalink: 'rewqu',
        permalink_url: 'https://soundcloud.com/rewqu',
        uri: 'https://api.soundcloud.com/users/974750107',
        urn: 'soundcloud:users:974750107',
        username: 'réwqu',
        verified: false,
        city: '',
        country_code: 'TR',
        badges: {
          pro: false,
          creator_mid_tier: false,
          pro_unlimited: true,
          verified: false,
        },
        station_urn: 'soundcloud:system-playlists:artist-stations:974750107',
        station_permalink: 'artist-stations:974750107',
      },
    },
  ],
  track_count: 2,
};
